name: CI
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ (github.head_ref || github.ref_name) == 'main' }}
    environment: openplanet-snake.danonthemoon.dev
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: api
          push: true
          tags: danonthemoon/openplanet-snake-api:latest
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Helm Upgrade
        shell: bash
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 240 ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}
          helm dependency update ./helm/openplanet-snake
          helm -n openplanet-snake upgrade --install --wait --timeout 60s --atomic openplanet-snake ./helm/openplanet-snake/
